/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;

import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author pc
 */
public class Acceuil extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Acceuil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelIdentification = new javax.swing.JLabel();
        LabelLogin = new javax.swing.JLabel();
        TFLogin = new javax.swing.JTextField();
        TFPassword = new javax.swing.JPasswordField();
        LabelPassword = new javax.swing.JLabel();
        BConnecter = new javax.swing.JButton();
        BQuitter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");

        LabelIdentification.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LabelIdentification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        LabelLogin.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        LabelLogin.setText("Identifiant       :");

        LabelPassword.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        LabelPassword.setText("Mot de Passe  :");

        BConnecter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BConnecter.setText("Login");
        BConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConnecterActionPerformed(evt);
            }
        });

        BQuitter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BQuitter.setText("Quitter");
        BQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BQuitterActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setText("Login");


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(176)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(LabelPassword, GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE)
        				.addComponent(LabelLogin))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(51)
        					.addComponent(TFPassword, GroupLayout.PREFERRED_SIZE, 166, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(TFLogin, GroupLayout.PREFERRED_SIZE, 166, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(121, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(88)
        			.addComponent(BConnecter, GroupLayout.PREFERRED_SIZE, 166, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
        			.addComponent(BQuitter, GroupLayout.PREFERRED_SIZE, 166, GroupLayout.PREFERRED_SIZE)
        			.addGap(91))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(430, Short.MAX_VALUE)
        			.addComponent(jLabel1)
        			.addGap(195))
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(LabelIdentification, GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        					.addGap(45)
        					.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
        					.addGap(252)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(LabelIdentification)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(102)
        					.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(TFLogin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(LabelLogin))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(LabelPassword)
        				.addComponent(TFPassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(25)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(BConnecter)
        				.addComponent(BQuitter))
        			.addGap(23)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        			.addGap(18))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConnecterActionPerformed
        // TODO add your handling code here:

        String pLogin = TFLogin.getText();
        String pPassword = charToString(TFPassword.getPassword());

        if(pLogin.equals("admin") && pPassword.equals("admin")){ 
            Menu_Principal FPrincipale = new Menu_Principal();
            FPrincipale.setVisible(true);
            this.dispose();
                    }
        else {
              JOptionPane.showMessageDialog(null,"Erreur ! Identifiant ou Mdp incorrecte");
              TFLogin.setText("");
              TFPassword.setText("");
             }

    }//GEN-LAST:event_BConnecterActionPerformed

    private void BQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BQuitterActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BQuitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuil().setVisible(true);
            }
        });
    }
    
public String charToString(char [] tabChar)
	{
		String str="";
		for(char c : tabChar)  str+=c;
		return str;
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BConnecter;
    private javax.swing.JButton BQuitter;
    private javax.swing.JLabel LabelIdentification;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JTextField TFLogin;
    private javax.swing.JPasswordField TFPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}


	
	