/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author pc
 */
public class Ajout_Employe extends javax.swing.JFrame {
 Statement stmt;
 ConnexionSQL maConnexion=new ConnexionSQL();
    /**
     * Creates new form FenetreAjout
     */
    public Ajout_Employe() {
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelNom = new javax.swing.JLabel();
        LabelPrenom = new javax.swing.JLabel();
        LabelAge = new javax.swing.JLabel();
        LabelPoste = new javax.swing.JLabel();
        LabelSalaire = new javax.swing.JLabel();
        TFNom = new javax.swing.JTextField();
        TFPrenom = new javax.swing.JTextField();
        TFAge = new javax.swing.JTextField();
        TFPoste = new javax.swing.JTextField();
        TFSalaire = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajouter");

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFocusable(false);

        LabelNom.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        LabelNom.setText("Nom      :");

        LabelPrenom.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        LabelPrenom.setText("Prenom :");

        LabelAge.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        LabelAge.setText("Age       :");

        LabelPoste.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        LabelPoste.setText("Poste     :");

        LabelSalaire.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        LabelSalaire.setText("Salaire   :");

        TFNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNomActionPerformed(evt);
            }
        });

        TFPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPrenomActionPerformed(evt);
            }
        });

        TFAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAgeActionPerformed(evt);
            }
        });

        TFPoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPosteActionPerformed(evt);
            }
        });

        TFSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSalaireActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel2.setText(" Id         :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(95, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(LabelNom)
        				.addComponent(LabelPrenom)
        				.addComponent(LabelPoste, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jLabel2)
        				.addComponent(LabelSalaire, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(LabelAge, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGap(33)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(TFPoste, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)
        				.addComponent(TFAge, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)
        				.addComponent(TFSalaire, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)
        				.addComponent(TFPrenom, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)
        				.addComponent(TFNom, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)
        				.addComponent(TFId, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE))
        			.addGap(146))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        				.addComponent(TFId, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(11)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(TFNom, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(LabelNom))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(TFPrenom, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(LabelPrenom))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(TFAge, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(LabelAge))
        			.addPreferredGap(ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(LabelPoste)
        				.addComponent(TFPoste, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(TFSalaire, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(LabelSalaire, GroupLayout.PREFERRED_SIZE, 13, GroupLayout.PREFERRED_SIZE))
        			.addGap(32))
        );
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajouter un Employé");

        jButton1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton1.setText("Quitter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BAnnuler = new javax.swing.JButton();
        
                BAnnuler.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
                BAnnuler.setText("Annuler");
                BAnnuler.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        BAnnulerActionPerformed(evt);
                    }
                });
        BValider = new javax.swing.JButton();
        
                BValider.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
                BValider.setText("Valider");
                BValider.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        BValiderActionPerformed(evt);
                    }
                });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(9)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addGap(51)
        					.addComponent(BValider, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
        					.addGap(131)
        					.addComponent(BAnnuler)
        					.addGap(140)
        					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(35)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(BAnnuler)
        				.addComponent(BValider))
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TFNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNomActionPerformed

    private void TFPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFPrenomActionPerformed

    private void TFAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAgeActionPerformed

    private void TFPosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPosteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFPosteActionPerformed

    private void TFSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSalaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSalaireActionPerformed

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        // TODO add your handling code here:
        String Id = TFId.getText();
        String Nom = TFNom.getText();
        String Prenom = TFPrenom.getText();
        String Age = TFAge.getText();
        String Poste = TFPoste.getText();
        String Salaire = TFSalaire.getText();
        String requete = "Insert into Employe values("+Id+",'"+Nom+"','"+Prenom+"',"+Age+",'"+Poste+"',"+Salaire+")"  ;
            try{
                stmt=maConnexion.ObtenirConnexion().createStatement();
                //stmt.executeQuery(requete); // ExecuteQuery ne passe jamais pour l'insertion d'une valeur dans une base mysql
                stmt.executeUpdate(requete); 
                
               JOptionPane.showMessageDialog(null,"Employé ajouté !");
               TFId.setText("");
               TFNom.setText("");
               TFPrenom.setText("");
               TFAge.setText("");
               TFPoste.setText("");
               TFSalaire.setText("");
 
            } 
            catch(SQLException ex) {System.err.println(ex);
                          }

    }//GEN-LAST:event_BValiderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
        TFId.setText("");
        TFNom.setText("");
        TFPrenom.setText("");
        TFAge.setText("");
        TFPoste.setText("");
        TFSalaire.setText("");
        
    }//GEN-LAST:event_BAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajout_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajout_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajout_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajout_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajout_Employe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BValider;
    private javax.swing.JLabel LabelAge;
    private javax.swing.JLabel LabelNom;
    private javax.swing.JLabel LabelPoste;
    private javax.swing.JLabel LabelPrenom;
    private javax.swing.JLabel LabelSalaire;
    private javax.swing.JTextField TFAge;
    private javax.swing.JTextField TFId;
    private javax.swing.JTextField TFNom;
    private javax.swing.JTextField TFPoste;
    private javax.swing.JTextField TFPrenom;
    private javax.swing.JTextField TFSalaire;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
