/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author pc
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form FenetreMain
     */
    public Menu_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BChercherE = new javax.swing.JButton();
        BAjouterE = new javax.swing.JButton();
        BSupprimerE = new javax.swing.JButton();
        BModifierE = new javax.swing.JButton();
        BAfficherE = new javax.swing.JButton();
        LabelSuppressionE = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        setTitle("Gestion des employés");

        BChercherE.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BChercherE.setText("Rechercher");
        BChercherE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BChercherEActionPerformed(evt);
            }
        });

        BAjouterE.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BAjouterE.setText("Ajouter ");
        BAjouterE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAjouterEActionPerformed(evt);
            }
        });

        BSupprimerE.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BSupprimerE.setText("Supprimer");
        BSupprimerE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSupprimerEActionPerformed(evt);
            }
        });

        BModifierE.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BModifierE.setText("Modifier");
        BModifierE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModifierEActionPerformed(evt);
            }
        });

        BAfficherE.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BAfficherE.setText("Afficher");
        BAfficherE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAfficherEActionPerformed(evt);
            }
        });

        LabelSuppressionE.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        LabelSuppressionE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSuppressionE.setText("Gestion des employés");

        setJMenuBar(Menu);
        BQuitter = new javax.swing.JButton();
        
                BQuitter.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
                BQuitter.setText("Quitter");
                BQuitter.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        BQuitterActionPerformed(evt);
                    }
                });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(168)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(BSupprimerE, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        				.addComponent(BModifierE, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        				.addComponent(BAfficherE, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        				.addComponent(BChercherE, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        				.addComponent(BAjouterE, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        			.addGap(205))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(114)
        			.addComponent(LabelSuppressionE, GroupLayout.PREFERRED_SIZE, 232, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(146, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(189)
        			.addComponent(BQuitter)
        			.addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addComponent(LabelSuppressionE, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
        			.addGap(25)
        			.addComponent(BAjouterE)
        			.addGap(18)
        			.addComponent(BChercherE)
        			.addGap(18)
        			.addComponent(BAfficherE)
        			.addGap(18)
        			.addComponent(BModifierE)
        			.addGap(18)
        			.addComponent(BSupprimerE)
        			.addGap(40)
        			.addComponent(BQuitter)
        			.addContainerGap(90, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BAjouterEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAjouterEActionPerformed

        // TODO add your handling code here:
        Ajout_Employe FAjout = new Ajout_Employe();
        FAjout.setVisible(true);
    }//GEN-LAST:event_BAjouterEActionPerformed

    private void BModifierEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModifierEActionPerformed
        // TODO add your handling code here:
        Modification_Employe FModification = new Modification_Employe();
        FModification.setVisible(true);
    }//GEN-LAST:event_BModifierEActionPerformed

    private void BAfficherEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAfficherEActionPerformed
        // TODO add your handling code here:
        Affichage_Employes FAffichage = new Affichage_Employes();
        FAffichage.setVisible(true);

    }//GEN-LAST:event_BAfficherEActionPerformed

    private void BQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BQuitterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BQuitterActionPerformed

    private void BSupprimerEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSupprimerEActionPerformed
        // TODO add your handling code here:
        Supression_Employe FSuppression = new Supression_Employe();
        FSuppression.setVisible(true);
        
    }//GEN-LAST:event_BSupprimerEActionPerformed

    private void BChercherEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BChercherEActionPerformed
        // TODO add your handling code here:
        Recherche_Employe FRecherche = new Recherche_Employe();
        FRecherche.setVisible(true);
    }//GEN-LAST:event_BChercherEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAfficherE;
    private javax.swing.JButton BAjouterE;
    private javax.swing.JButton BChercherE;
    private javax.swing.JButton BModifierE;
    private javax.swing.JButton BQuitter;
    private javax.swing.JButton BSupprimerE;
    private javax.swing.JLabel LabelSuppressionE;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    // End of variables declaration//GEN-END:variables
}
