/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
/**
 *
 * @author pc
 */
public class Modification_Employe extends javax.swing.JFrame {

 Statement stmt;
 ConnexionSQL maConnexion=new ConnexionSQL();

    /**
     * Creates new form FenetreModification
     */
    public Modification_Employe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelModification = new javax.swing.JLabel();
        LabelPoste = new javax.swing.JLabel();
        TFId = new javax.swing.JTextField();
        LabelSalaire = new javax.swing.JLabel();
        LabelNumero = new javax.swing.JLabel();
        TFPoste = new javax.swing.JTextField();
        TFSalaire = new javax.swing.JTextField();
        BQuitter = new javax.swing.JButton();
        BValider = new javax.swing.JButton();
        BAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modifier");
        setFocusCycleRoot(false);
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);

        LabelModification.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LabelModification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelModification.setText("Modification d'un employé");

        LabelPoste.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        LabelPoste.setText("Nouveau Poste                    :");

        LabelSalaire.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        LabelSalaire.setText("Nouveau Salaire                  :");

        LabelNumero.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        LabelNumero.setText("ID                                      :");

        BQuitter.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BQuitter.setText("Quitter");
        BQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BQuitterActionPerformed(evt);
            }
        });

        BValider.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BValider.setText("Valider");
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });

        BAnnuler.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BAnnuler.setText("Annuler");
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(LabelModification, GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(0, 100, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(LabelNumero, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(LabelPoste, 0, 0, Short.MAX_VALUE)
        						.addComponent(LabelSalaire))
        					.addGap(38)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(TFPoste, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
        						.addComponent(TFSalaire, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
        						.addComponent(TFId, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE))
        					.addGap(89))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(49)
        					.addComponent(BValider, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
        					.addGap(122)
        					.addComponent(BAnnuler)
        					.addPreferredGap(ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
        					.addComponent(BQuitter, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)
        					.addGap(52))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(15)
        			.addComponent(LabelModification, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        			.addGap(87)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(LabelNumero)
        				.addComponent(TFId, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(LabelPoste)
        				.addComponent(TFPoste, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(19)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(LabelSalaire)
        				.addComponent(TFSalaire, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(BValider)
        				.addComponent(BAnnuler)
        				.addComponent(BQuitter))
        			.addGap(19))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BQuitterActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_BQuitterActionPerformed

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        // TODO add your handling code here:
        
                String pNum = TFId.getText();
                String pPoste = TFPoste.getText();
                String pSalaire = TFSalaire.getText();

                String requete = "Update Employe set Poste='"+pPoste+"',Salaire='"+pSalaire+"'"+"where Id="+pNum+"" ;
               try{
                stmt=maConnexion.ObtenirConnexion().createStatement();
                //stmt.executeQuery(requete); // ExecuteQuery ne passe jamais pour l'insertion d'une valeur dans une base mysql
                stmt.executeUpdate(requete); 
                
               JOptionPane.showMessageDialog(null,"Employé modifié");
               TFId.setText("");
               TFPoste.setText("");
               TFSalaire.setText("");
     
            } 
            catch(SQLException ex) {System.err.println(ex);}
    }//GEN-LAST:event_BValiderActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
        TFId.setText("");
        TFPoste.setText("");
        TFSalaire.setText("");
    }//GEN-LAST:event_BAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modification_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modification_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modification_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modification_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modification_Employe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BQuitter;
    private javax.swing.JButton BValider;
    private javax.swing.JLabel LabelModification;
    private javax.swing.JLabel LabelNumero;
    private javax.swing.JLabel LabelPoste;
    private javax.swing.JLabel LabelSalaire;
    private javax.swing.JTextField TFId;
    private javax.swing.JTextField TFPoste;
    private javax.swing.JTextField TFSalaire;
    // End of variables declaration//GEN-END:variables
}
