/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
/**
 *
 * @author pc
 */
public class Recherche_Employe extends javax.swing.JFrame {
    Statement stmt;
    ConnexionSQL maConnexion=new ConnexionSQL();

    /**
     * Creates new form FenetreRecherche
     */
    public Recherche_Employe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelRecherche = new javax.swing.JLabel();
        LabelNumero = new javax.swing.JLabel();
        TFId = new javax.swing.JTextField();
        BAnnuler = new javax.swing.JButton();
        BValider = new javax.swing.JButton();
        BQuitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rechercher");
        setBackground(new java.awt.Color(255, 0, 0));

        LabelRecherche.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LabelRecherche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelRecherche.setText("Recherche d'un employé");

        LabelNumero.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        LabelNumero.setText("ID :");

        BAnnuler.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BAnnuler.setText("Annuler");
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });

        BValider.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BValider.setText("Rechercher");
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });

        BQuitter.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BQuitter.setText("Quitter");
        BQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BQuitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(29)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(BValider, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
        					.addGap(88)
        					.addComponent(BAnnuler, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(84)
        					.addComponent(LabelNumero, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
        					.addGap(26)
        					.addComponent(TFId, GroupLayout.PREFERRED_SIZE, 205, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(435, Short.MAX_VALUE)
        			.addComponent(BQuitter, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
        			.addGap(30))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(LabelRecherche, GroupLayout.PREFERRED_SIZE, 559, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap(80, Short.MAX_VALUE)
        			.addComponent(LabelRecherche, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
        			.addGap(31)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(LabelNumero, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        				.addComponent(TFId, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
        			.addGap(117)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(BQuitter)
        				.addComponent(BValider)
        				.addComponent(BAnnuler))
        			.addGap(32))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
        TFId.setText("");
    }//GEN-LAST:event_BAnnulerActionPerformed

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        // TODO add your handling code here:

        String Id = TFId.getText();
        String requete = "Select * from Employe where Id="+Id+"";
        try{
            stmt=maConnexion.ObtenirConnexion().createStatement();
            //stmt.executeQuery(requete); // ExecuteQuery ne passe jamais pour l'insertion d'une valeur dans une base mysql
            ResultSet resultat = stmt.executeQuery(requete);
            resultat.last();
            int nbrRow = resultat.getRow();
            if (nbrRow!=0) {JOptionPane.showMessageDialog(null,"L'employé avec ID"+Id+" existe");
}
            else { JOptionPane.showMessageDialog(null,"Employé ID"+Id+" n'existe pas !");
}

            TFId.setText("");

        }
        catch(SQLException ex) {System.err.println(ex);}
    }//GEN-LAST:event_BValiderActionPerformed

    private void BQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BQuitterActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BQuitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recherche_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recherche_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recherche_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recherche_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recherche_Employe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BQuitter;
    private javax.swing.JButton BValider;
    private javax.swing.JLabel LabelNumero;
    private javax.swing.JLabel LabelRecherche;
    private javax.swing.JTextField TFId;
    // End of variables declaration//GEN-END:variables
}
