/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
/**
 *
 * @author pc
 */
public class Supression_Employe extends javax.swing.JFrame {
 Statement stmt;
 ConnexionSQL maConnexion=new ConnexionSQL();

    /**
     * Creates new form FenetreSuppression
     */
    public Supression_Employe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelSuppression = new javax.swing.JLabel();
        LabelNumero = new javax.swing.JLabel();
        TFNumero = new javax.swing.JTextField();
        BValider = new javax.swing.JButton();
        BQuitter = new javax.swing.JButton();
        BAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        setTitle("Supprimer");

        LabelSuppression.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LabelSuppression.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSuppression.setText("Suppression d'un employé");

        LabelNumero.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        LabelNumero.setText("ID :");

        BValider.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BValider.setText("Valider");
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });

        BQuitter.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BQuitter.setText("Quitter");
        BQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BQuitterActionPerformed(evt);
            }
        });

        BAnnuler.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        BAnnuler.setText("Annuler");
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(69)
        					.addComponent(BValider, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(86)
        					.addComponent(LabelNumero, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
        					.addComponent(BAnnuler, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
        					.addGap(84)
        					.addComponent(BQuitter, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
        					.addGap(26))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(23)
        					.addComponent(TFNumero, GroupLayout.PREFERRED_SIZE, 199, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(LabelSuppression, GroupLayout.PREFERRED_SIZE, 577, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(73, Short.MAX_VALUE)
        			.addComponent(LabelSuppression, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        			.addGap(50)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(LabelNumero, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        				.addComponent(TFNumero, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
        			.addGap(97)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(BQuitter)
        				.addComponent(BAnnuler)
        				.addComponent(BValider))
        			.addGap(31))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BQuitterActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BQuitterActionPerformed

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        // TODO add your handling code here:
        
                String Num = TFNumero.getText();
                String requete = "Delete from Employe where Id="+Num;
               try{
                stmt=maConnexion.ObtenirConnexion().createStatement();
                //stmt.executeQuery(requete); // ExecuteQuery ne passe jamais pour l'insertion d'une valeur dans une base mysql
                stmt.executeUpdate(requete); 
                
               JOptionPane.showMessageDialog(null,"Employé supprimé !");
               TFNumero.setText("");
     
            } 
            catch(SQLException ex) {System.err.println(ex);}

    }//GEN-LAST:event_BValiderActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
         TFNumero.setText("");
    }//GEN-LAST:event_BAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supression_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supression_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supression_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supression_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supression_Employe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BQuitter;
    private javax.swing.JButton BValider;
    private javax.swing.JLabel LabelNumero;
    private javax.swing.JLabel LabelSuppression;
    private javax.swing.JTextField TFNumero;
    // End of variables declaration//GEN-END:variables
}
